<a href="https://colab.research.google.com/github/hokoro/DataAnalyze/blob/main/Numpy/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3,5)
print(a)
print(f'a.shape: {a.shape}') # ndarray 의 배열의 모양
print(f'a.ndim: {a.ndim}') # ndarray 의 차원
print(f'a.dtype.name: {a.dtype.name}') # ndarray 의 데이터 타입
print(f'a.itemsize: {a.itemsize}') # ndarray 의 바이트 크기
print(f'a.size: {a.size}') # ndarray 의 총개수
print(f'type(a): {type(a)}') # ndarray 의 타입

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape: (3, 5)
a.ndim: 2
a.dtype.name: int64
a.itemsize: 8
a.size: 15
type(a): <class 'numpy.ndarray'>


In [5]:
a= np.array([1,2,3,4]) # np.array(list)
print(a)
print(type(a))
print(a.dtype)


b = np.array([1.5,2.5,5.1])
print(b)
print(type(b))
print(b.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
[1.5 2.5 5.1]
<class 'numpy.ndarray'>
float64


In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
d = np.array([[1,2],[3,4]] , dtype = complex)
print(d)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
