<a href="https://colab.research.google.com/github/hokoro/DataAnalyze/blob/main/Numpy/numpy_function2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.arange(6).reshape((2,3))
b = np.zeros_like(a)

In [4]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]


In [5]:
c = np.arange(6).reshape((2,3))
d = np.ones_like(c)

In [6]:
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


In [7]:
e = ([1,2,3],[4,5,6])
e_like = np.empty_like(e)

print(e)
print(e_like)

([1, 2, 3], [4, 5, 6])
[[57941152        0        0]
 [       0        0        0]]


In [8]:
f = ([1.,2.,3.] , [4.,5.,6.])
f_like = np.empty_like(f)

In [9]:
print(f)
print(f_like)

([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
[[2.92733026e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [12]:
g = np.full((2,3),np.inf)
print(g)

h = np.full((2,3),5)
print(h)

[[inf inf inf]
 [inf inf inf]]
[[5 5 5]
 [5 5 5]]


In [19]:
i = np.arange(5 , dtype = int)
i_full_like = np.full_like(i,5) # dtype 에 맞는 형태로 full_like 수행



In [17]:
i_full_like

array([1, 1, 1, 1, 1])