<a href="https://colab.research.google.com/github/hokoro/DataAnalyze/blob/main/Numpy/numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.zeros(10)
print(a)

b = np.ones(10)
print(b)

c = np.empty((2,3))
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[2.3944168e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [3]:
d = np.arange(1,10,2)
print(d)

[1 3 5 7 9]


In [4]:
e = np.linspace(0,2,9)
print(e)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
